'use server';
/**
 * @fileOverview This file defines a Genkit flow for answering questions about documents.
 *
 * - answerQuestionsAboutDocuments - A function that takes a question and a list of documents as input and returns an answer generated by AI.
 * - AnswerQuestionsAboutDocumentsInput - The input type for the answerQuestionsAboutDocuments function.
 * - AnswerQuestionsAboutDocumentsOutput - The return type for the answerQuestionsAboutDocuments function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

export type AnswerQuestionsAboutDocumentsInput = {
  question: string;
  documents: string[];
};

export type AnswerQuestionsAboutDocumentsOutput = {
  answer: string;
  citations?: {
    citationNumber: number;
    document: string;
    passage: string;
  }[];
};

const AnswerQuestionsAboutDocumentsInputSchema = z.object({
  question: z.string().describe('The question to answer about the documents.'),
  documents: z.array(z.string()).describe('The list of documents to use as context for answering the question.'),
});

const AnswerQuestionsAboutDocumentsOutputSchema = z.object({
  answer: z.string().describe("The answer to the question, generated by AI. This answer should include inline citation numbers, like [1], [2], etc., corresponding to the 'citations' array."),
  citations: z.array(z.object({
    citationNumber: z.number().describe('The citation number (e.g., 1, 2, 3) that links to this source in the answer text.'),
    document: z.string().describe('The name of the document cited. This should match the format "Document Name: <name>" from the input.'),
    passage: z.string().describe('The relevant passage from the document.'),
  })).optional().describe('Citations for the answer.'),
});

export async function answerQuestionsAboutDocuments(input: AnswerQuestionsAboutDocumentsInput): Promise<AnswerQuestionsAboutDocumentsOutput> {
  return answerQuestionsAboutDocumentsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerQuestionsAboutDocumentsPrompt',
  input: {schema: AnswerQuestionsAboutDocumentsInputSchema},
  output: {schema: AnswerQuestionsAboutDocumentsOutputSchema},
  prompt: `You are an AI assistant that answers questions based on a provided set of documents.

  Your task is to:
  1.  Carefully read the user's question and the content of the provided documents.
  2.  Formulate a comprehensive answer to the question using only the information available in the documents.
  3.  As you write the answer, you MUST include inline citations. An inline citation is a number in brackets, like [1], placed directly after the sentence or claim that is supported by a document.
  4.  For each inline citation number you use, you MUST create a corresponding entry in the 'citations' array in the output.
  5.  Each entry in the 'citations' array must contain:
      - 'citationNumber': The number you used in the answer text (e.g., 1, 2, 3).
      - 'document': The name of the source document, exactly as it appears in the input (e.g., "Document Name: quarterly_report.pdf").
      - 'passage': The exact, verbatim quote from the document that supports the claim.
  6.  Ensure that every citation number in the answer text has a matching object in the 'citations' array.
  7.  If you cannot answer the question based on the documents, state that clearly.
  8.  Format your final answer in Markdown.

  Question: {{{question}}}

  Documents:
  {{#each documents}}
  ---
  {{{this}}}
  {{/each}}
  `,
});

const answerQuestionsAboutDocumentsFlow = ai.defineFlow(
  {
    name: 'answerQuestionsAboutDocumentsFlow',
    inputSchema: AnswerQuestionsAboutDocumentsInputSchema,
    outputSchema: AnswerQuestionsAboutDocumentsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
