'use server';
/**
 * @fileOverview This file defines a Genkit flow for answering questions about documents.
 *
 * - answerQuestionsAboutDocuments - A function that takes a question and a list of documents as input and returns an answer generated by AI.
 * - AnswerQuestionsAboutDocumentsInput - The input type for the answerQuestionsAboutDocuments function.
 * - AnswerQuestionsAboutDocumentsOutput - The return type for the answerQuestionsAboutDocuments function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerQuestionsAboutDocumentsInputSchema = z.object({
  question: z.string().describe('The question to answer about the documents.'),
  documents: z.array(z.string()).describe('The list of documents to use as context for answering the question.'),
});
export type AnswerQuestionsAboutDocumentsInput = z.infer<typeof AnswerQuestionsAboutDocumentsInputSchema>;

const AnswerQuestionsAboutDocumentsOutputSchema = z.object({
  answer: z.string().describe('The answer to the question, generated by AI.'),
  citations: z.array(z.object({
    document: z.string().describe('The name of the document cited.'),
    passage: z.string().describe('The relevant passage from the document.'),
  })).optional().describe('Citations for the answer.'),
});
export type AnswerQuestionsAboutDocumentsOutput = z.infer<typeof AnswerQuestionsAboutDocumentsOutputSchema>;

export async function answerQuestionsAboutDocuments(input: AnswerQuestionsAboutDocumentsInput): Promise<AnswerQuestionsAboutDocumentsOutput> {
  return answerQuestionsAboutDocumentsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerQuestionsAboutDocumentsPrompt',
  input: {schema: AnswerQuestionsAboutDocumentsInputSchema},
  output: {schema: AnswerQuestionsAboutDocumentsOutputSchema},
  prompt: `You are an AI assistant that answers questions about documents.

  You are given a question and a list of documents. You should answer the question based on the information in the documents.
  If you are unable to answer the question based on the information in the documents, you should say that you don't know.

  Question: {{{question}}}

  Documents:
  {{#each documents}}
  ---
  {{{this}}}
  {{/each}}

  Answer in markdown format. Include citations to the documents and passages that support your answer.
  `,
});

const answerQuestionsAboutDocumentsFlow = ai.defineFlow(
  {
    name: 'answerQuestionsAboutDocumentsFlow',
    inputSchema: AnswerQuestionsAboutDocumentsInputSchema,
    outputSchema: AnswerQuestionsAboutDocumentsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
