'use server';
/**
 * @fileOverview This file defines a Genkit flow for answering questions using both a given set of documents and a web search.
 *
 * - answerQuestionsUsingDocumentsAndWeb - A function that takes a question and documents, performs a web search, and returns a synthesized answer.
 * - AnswerQuestionsUsingDocumentsAndWebInput - The input type for the function.
 * - AnswerQuestionsUsingDocumentsAndWebOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerQuestionsUsingDocumentsAndWebInputSchema = z.object({
  question: z.string().describe('The question to answer.'),
  documents: z.array(z.string()).describe('A list of documents to use as primary context.'),
});
export type AnswerQuestionsUsingDocumentsAndWebInput = z.infer<typeof AnswerQuestionsUsingDocumentsAndWebInputSchema>;

// The output schema can be the same as the document-only version for consistency.
const AnswerQuestionsUsingDocumentsAndWebOutputSchema = z.object({
  answer: z.string().describe("The answer to the question, generated by AI. This answer should include inline citation numbers, like [1], [2], etc., corresponding to the 'citations' array."),
  citations: z.array(z.object({
    citationNumber: z.number().describe('The citation number (e.g., 1, 2, 3) that links to this source in the answer text.'),
    document: z.string().describe('The name of the document or "Web Search" if the source is from the web.'),
    passage: z.string().describe('The relevant passage from the document or web result.'),
  })).optional().describe('Citations for the answer.'),
});
export type AnswerQuestionsUsingDocumentsAndWebOutput = z.infer<typeof AnswerQuestionsUsingDocumentsAndWebOutputSchema>;

export async function answerQuestionsUsingDocumentsAndWeb(input: AnswerQuestionsUsingDocumentsAndWebInput): Promise<AnswerQuestionsUsingDocumentsAndWebOutput> {
  return answerQuestionsUsingDocumentsAndWebFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerQuestionsUsingDocumentsAndWebPrompt',
  input: {schema: AnswerQuestionsUsingDocumentsAndWebInputSchema},
  output: {schema: AnswerQuestionsUsingDocumentsAndWebOutputSchema},
  tools: [ai.googleSearch],
  prompt: `You are an expert research assistant. Your goal is to provide a comprehensive and accurate answer to the user's question by synthesizing information from two sources: a provided set of documents and a web search.

  Your task is to:
  1.  First, carefully read the user's question and the content of the provided documents. Prioritize information from these documents in your answer.
  2.  Next, use the web search tool to find additional, complementary, or more up-to-date information that the documents may not contain.
  3.  Synthesize the information from both the documents and the web search to construct a single, cohesive answer.
  4.  As you write the answer, you MUST include inline citations. A citation for a document is a number in brackets, like [1]. A citation from a web search should also be a number in brackets like [2].
  5.  For each inline citation, you MUST create a corresponding entry in the 'citations' array.
  6.  Each entry in the 'citations' array must contain:
      - 'citationNumber': The number you used in the answer (e.g., 1, 2, 3).
      - 'document': The name of the source document, or "Web Search" if the information came from the web tool.
      - 'passage': The exact, verbatim quote from the document or web search result that supports the claim.
  7.  Ensure that every claim in your answer is supported by a citation.
  8.  If you cannot answer the question using the provided sources, state that clearly.
  9.  Format your final answer in Markdown.

  Question: {{{question}}}

  Documents:
  {{#each documents}}
  ---
  {{{this}}}
  {{/each}}
  `,
});

const answerQuestionsUsingDocumentsAndWebFlow = ai.defineFlow(
  {
    name: 'answerQuestionsUsingDocumentsAndWebFlow',
    inputSchema: AnswerQuestionsUsingDocumentsAndWebInputSchema,
    outputSchema: AnswerQuestionsUsingDocumentsAndWebOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
